FROM mcr.microsoft.com/dotnet/core/sdk:3.1
RUN dotnet tool install --global dotnet-ef
RUN dotnet tool install --global dotnet-aspnet-codegenerator
ADD ./app /app
ENV PATH=/root/.dotnet/tools:$PATH
RUN cd app && dotnet restore
